# Generate the firmware build stamp reported in the telemetry "fw" field.
#
# Run in script mode (cmake -P) from a custom target so the timestamp is taken
# at build time, not at configure time - a configure-time value would go stale
# the moment you rebuilt without reconfiguring, which is exactly when a build
# stamp is least allowed to lie.
#
# Expects OUTPUT_FILE to be set by the caller.
#
# SPDX-License-Identifier: Apache-2.0

# UTC, so the stamp is comparable with the timestamps the cloud providers put on
# the records themselves regardless of where the image was built.
string(TIMESTAMP stamp "%Y-%m-%dT%H:%MZ" UTC)

set(content "\
/* Generated by cmake/build_stamp.cmake - do not edit. */
#ifndef TRACKER_BUILD_STAMP_H_
#define TRACKER_BUILD_STAMP_H_

#define TRACKER_BUILD_STAMP \"${stamp}\"

#endif /* TRACKER_BUILD_STAMP_H_ */
")

# Only rewrite when the minute has actually rolled over. Touching the header
# unconditionally would recompile telemetry.c and relink on every single build.
set(existing "")
if(EXISTS "${OUTPUT_FILE}")
	file(READ "${OUTPUT_FILE}" existing)
endif()

if(NOT existing STREQUAL content)
	file(WRITE "${OUTPUT_FILE}" "${content}")
endif()
