# Disable nPM1300 / peripherals not needed inside the bootloader.
CONFIG_MFD_NPM13XX=n
CONFIG_GPIO_NPM13XX=n

# Multithreading
CONFIG_MULTITHREADING=y

# MCUBoot settings
CONFIG_BOOT_MAX_IMG_SECTORS=256
