/*
 * Telemetry payload builder.
 *
 * Produces the *inner* JSON string that the web-app/backend already expects:
 *
 *   {"coords": [<lon>, <lat>], "hdop": <h>, "batt": <pct>, "volt": <mV>,
 *    "charge": <state>, "signal": <rsrp_dbm>, "awake": <secs>,
 *    "vbus": <bool>, "wake": "<reason>", "wdt": <phase>,
 *    "fw": "<build stamp>", "hw": "<revision>"}
 *
 * "fw" is the UTC build time (TRACKER_BUILD_STAMP, generated by
 * cmake/build_stamp.cmake), not a semantic version: nothing has to be
 * remembered or bumped, and it sorts chronologically as plain text.
 *
 * "wdt" is the enum tracker_phase the report loop was in when the watchdog last
 * reset the device, or 0 if the last boot was clean. Sticky until the next
 * reset, so it can be read off any record rather than just the one after.
 *
 * The first seven fields are byte-compatible with the original Hologram Dash
 * sketch, except that "charge" now carries tracker_charge_state (0/1/2) rather
 * than the Dash's charge_status (0/2/4/7) - the two enumerations collide on
 * every value they share, so the reader must know which board sent the record.
 * Which is exactly what the trailing "fw"/"hw" pair is for.
 *
 * New fields are appended, never inserted, so the prefix of an old record and a
 * new one stay comparable.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef GPS_TRACKER_TELEMETRY_H_
#define GPS_TRACKER_TELEMETRY_H_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "power.h"
#include "wake.h"

struct tracker_telemetry {
	double longitude;
	double latitude;
	float hdop;
	uint16_t batt_mv;
	enum tracker_charge_state charge;
	int signal_dbm; /* RSRP in dBm (negative); replaces the Dash CSQ value */
	uint32_t awake_s;
	/* External power present. Independent of @ref charge, which reports only
	 * what the charger is doing: plugged in with the charger idle reads as
	 * vbus true, charge 0.
	 */
	bool vbus;
	/* Why the *cycle* started, so every report in a motion surge is tagged
	 * "motion" even once external power arrives - that is what makes a surge
	 * identifiable as one event rather than a run of unrelated points.
	 */
	enum tracker_wake_reason wake;
};

/**
 * @brief Estimate battery percentage (0-100) from voltage using a LiPo curve.
 */
uint8_t telemetry_battery_percent(uint16_t batt_mv);

/**
 * @brief Build the inner telemetry JSON string.
 *
 * @param t     Telemetry values.
 * @param buf   Output buffer.
 * @param len   Size of @p buf.
 * @return number of bytes written (excluding NUL), or negative on truncation.
 */
int telemetry_build_json(const struct tracker_telemetry *t, char *buf, size_t len);

#endif /* GPS_TRACKER_TELEMETRY_H_ */
